#ifndef _HEADER_VERSION
#define _HEADER_VERSION

#define PROPANE_VERSION_MAJOR 1
#define PROPANE_VERSION_MINOR 1
#define PROPANE_VERSION_CHANGELIST 2312

// Minimum supported changelist
#define PROPANE_VERSION_CHANGELIST_MIN 2301

#endif